version: "3.9"
services:
  nginx:
    container_name: notification_nginx
    image: nginx:stable-alpine3.20-perl
    volumes:
    - ./nginx/:/etc/nginx/conf.d/
    - ./:/var/www/
    ports:
    - "80:80"
    depends_on:
    - php

  php:
    build: ./php
    container_name: notification_php
    # environment:
    volumes:
      - ./:/var/www/
    ports:
      - "9000:9000"

  postgres:
    container_name: notification_postgres
    image: postgres:16.1-alpine
    volumes:
      - notification:/var/lib/postgresql/data
    ports:
      - "54324:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: laravel

  rabbitmq:
    container_name: notification_rabbitmq
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
    notification:
